const menu=document.querySelector('.menu-toggle');
const nav=document.querySelector('.navlinks');
if(menu&&nav){menu.addEventListener('click',()=>{const open=nav.classList.toggle('mobile-open');menu.setAttribute('aria-expanded',open?'true':'false');menu.textContent=open?'×':'☰';});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('mobile-open');menu.setAttribute('aria-expanded','false');menu.textContent='☰';}));document.addEventListener('click',e=>{if(!nav.contains(e.target)&&!menu.contains(e.target)){nav.classList.remove('mobile-open');menu.setAttribute('aria-expanded','false');menu.textContent='☰';}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('mobile-open');menu.setAttribute('aria-expanded','false');menu.textContent='☰';}})}
const year=document.querySelector('[data-year]');if(year)year.textContent=new Date().getFullYear();
const reveals=document.querySelectorAll('.reveal');if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -60px'});reveals.forEach((el,i)=>{el.style.transitionDelay=Math.min((i%4)*70,210)+'ms';io.observe(el)})}else reveals.forEach(el=>el.classList.add('is-visible'));
window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--scroll',max>0?(scrollY/max*100)+'%':'0%');const hero=document.querySelector('.hero-bg');if(hero&&!matchMedia('(prefers-reduced-motion: reduce)').matches)hero.style.transform=`scale(1.06) translateY(${scrollY*.08}px)`},{passive:true});
const counts=document.querySelectorAll('[data-count]');if('IntersectionObserver'in window&&counts.length){const cio=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,end=Number(el.dataset.count),suffix=el.textContent.includes('%')?'%':'';const t0=performance.now();const tick=t=>{const p=Math.min((t-t0)/900,1),v=Math.round((1-Math.pow(1-p,3))*end);el.textContent=v+suffix;if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);cio.unobserve(el)}),{threshold:.8});counts.forEach(x=>cio.observe(x))}

/* Catalogue explorer: fast category filtering + search */
(function(){const input=document.querySelector('#catalogueSearch'),tiles=[...document.querySelectorAll('.catalogue-tile')],filters=[...document.querySelectorAll('.catalogue-filter, .catalogue-filter-light-btn')];if(!input||!tiles.length)return;let active='all';const apply=()=>{const q=input.value.trim().toLowerCase();tiles.forEach(t=>{const okCat=active==='all'||t.dataset.cat===active;const okText=!q||(t.dataset.search||'').toLowerCase().includes(q);t.hidden=!(okCat&&okText)});};filters.forEach(b=>b.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));b.classList.add('active');active=b.dataset.filter;apply()}));input.addEventListener('input',apply)})();
